#ifdef APDK_EXTENDED_MEDIASIZE
#define MAX_PRINTMODES 20
#else
#define MAX_PRINTMODES 10
#endif

#define GRAYMODE_INDEX 0
#define DEFAULTMODE_INDEX 1
#define SPECIALMODE_INDEX 2
#define EXTRASPECIALMODE_INDEX 3
